avoid false alarms for sites that aren't responsive during backup.

diff --git a/share/commands/site-reachable b/share/commands/site-reachable
--- a/share/commands/site-reachable
+++ b/share/commands/site-reachable
@@ -23,21 +23,36 @@ if [ -z "$sites" -o "$sites" = "--all" ]; then
   sites="$LONG_SITES"
 fi
 
-timeout=10
+retry_interval=120
 total_count=0
 online_count=0
 offline_count=0
+retry_sites=
 for site in $sites; do
   total_count=$(( $total_count + 1 ))
   # Ensure anonymous access to the page generates a login box.
-  if ! curl -s --max-time "$timeout" https://${site}.ourpowerbase.net  | grep "block-user-login" >/dev/null; then
-    offline_count=$(( $offline_count + 1 ))
-    long_log "Site %s is OFFLINE!!!" error "$site"
+  if ! long_is_site_reachable "$site"; then
+    # Some sites timeout during backups - so keep track of the ones that
+    # have timed out and retry them later.
+    retry_sites="$retry_sites $site"
   else
     online_count=$(( $online_count + 1 ))
     long_log "Site %s is online" info "$site"
   fi
 done
+
+if [ -n "$retry_sites" ]; then
+  long_log "Retrying sites after a %s second break: %s." info "$retry_interval" "$retry_sites"
+  # Wait a few minutes to let the backup completed.
+  sleep "$retry_interval"
+  for site in $retry_sites; do
+    if ! long_is_site_reachable "$site"; then
+      # Ensure 
+      offline_count=$(( $offline_count + 1 ))
+      long_log "Site %s is OFFLINE!!!" error "$site"
+    fi
+  done
+fi
 
 if [ -z "$quiet" ]; then
   printf "\nTotal checked: %s\n" "$total_count"
